### ISSUE TITLE
Support hyperlinks in descriptions

### ISSUE THREAD

**Issue by davidhay25** [HL7NZ/nzbase#11]
Some of the extensions and Valuesets have hyperlinks that are being rendered as text. Should be hyperlinks.

Example is nz-ethnicity

**Comment by pkjordan** [comment]
As of today, in the CB version - the following URLs are rendered as text, rather than hyperlinks ...
- Extensions Page - values in URL column (all resolvable so should be hyperlinks)
-  Profiles Page - values in URL column (not currently resolvable, but will be by publication time, so should be hyperlinks)
- Identifiers - values in URL column (these are not currently resolvable, so suggest leaving as text)

**Comment by pkjordan** [comment]
Work Group Meeting on August decided on the following changes...
Extensions Page -'Url' Column should be renamed 'Canonical URL' and the value should NOT be hyperlinked
Profiles Page - 'Url' Column should be renamed 'Canonical URL' and the value should NOT be hyperlinked
Terminology Page - the values in the 'ValueSet' & 'CodeSystem' Columns should be hyperlinked, but the values in the 'Canonical Url' columns should NOT be hyperlinked.

**Comment by pkjordan** [comment]
Completed.
