### ISSUE TITLE
Additional description text for NzContactPoint

### ISSUE THREAD

**Issue by jschealthnz** [HL7NZ/nzbase#46]
http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/StructureDefinition-NzContactPoint.html

Instead of "Common NZ ContactPoint datatype" how about

"This profile adds the Contact Point Purpose and EDI address extensions to the standard data type."

**Comment by pkjordan** [comment]
Looks good.

 

BTW: this is an example of a request for an (almost) human-readable version of a NZ extension via a Web Browser…

 

https:// <https://%20http:/hl7.org.nz/fhir/StructureDefinition/building-name/?_format=json&_pretty=true>  http://hl7.org.nz/fhir/StructureDefinition/building-name/?_format=json&_pretty=true

 

PJ

 

From: jschealthnz ***@***.***> 
Sent: Friday, 29 July 2022 11:54 am
To: HL7NZ/nzbase ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [HL7NZ/nzbase] Additional description text for NzContactPoint (Issue #46)

 

http://build.fhir.org/ig/HL7NZ/nzbase/branches/master/StructureDefinition-NzContactPoint.html

Instead of "Common NZ ContactPoint datatype" how about

"This profile adds the Contact Point Purpose and EDI address extensions to the standard data type."

**Comment by davidhay25** [comment]
description updated
