### ISSUE TITLE
Extension - educational-qualification shows that it can be used for Practitioner and Practitioner.qualification

### ISSUE THREAD

**Issue by roylecj2** [HL7NZ/nzbase#71]
In the extension it shows that educational-qualification can be used in both against the Practitioner level and within the practitioner.qualification level. When looking at the NZPractitioner profile it only shows within the Practitioner and not the Practitioner.qualification level - which one should it be?

**Comment by daniel-thomson** [comment]
I think this should be on Practitioner, not Practitioner.qualification (per the HPI's usage on the [profile](https://hpi-ig.hip-uat.digital.health.nz/StructureDefinition-HPIPractitioner.html) and examples - e.g. [this one](https://hpi-ig.hip-uat.digital.health.nz/Practitioner-91ZABY.json.html)). 

Allowing it on the Practitioner.qualification introduces confusion, as it is intended to be qualifications of the kind that aren't included in Practitioner.qualification (i.e. educational) . 

Changing status from approved to question to discuss next time, and proposing that instead of adding it to the profile level, we should actually remove this as an option from the extension.

**Comment by pkjordan** [comment]
Remove Practitioner Qualification from context of use.

**Comment by daniel-thomson** [comment]
done
