### ISSUE TITLE
Extension - messaging-address - link to Patient doesn't exist

### ISSUE THREAD

**Issue by roylecj2** [HL7NZ/nzbase#77]
The messaging-address says that the context is Patient, Location, Organization, HealthcareService, PractitionerRole and Practitioner - but against the NzPatient there is no messaging-address extension shown.

**Comment by daniel-thomson** [comment]
Should this be used on patient? (seems to be used for EDI which might cause confusion, but could be other messaging types...) 

Have made the update - but changing label to question for discussion next time (instead of closing) as this change was part of bulk approval of adding missing extensions to profiles, but want to be sure its intended.

**Comment by pkjordan** [comment]
Add extension to Patient Profile.

**Comment by daniel-thomson** [comment]
done
